###
GET http://localhost:5000/api/employees

###
POST http://localhost:5000/api/employees
Content-Type: application/json

{
    "name": "test",
    "position": "Dev",
    "office": "SP",
    "salary": "1000"
}

###
GET http://localhost:5000/api/employees/606327d60a01ed47602d9c24

###
DELETE http://localhost:5000/api/employees/606327d60a01ed47602d9c24

###
PUT http://localhost:5000/api/employees/606327d60a01ed47602d9c24
Content-Type: application/json

{
    "salary": 10000
}